Yanni 0530 updates:  
1. Map the indices into simple names and run the codes  
2. Do some simple analysis in the markdown
3. Use quarterly data to generate covariance matrices
4. Organize factor data(in org_data1.xlsx). For equity index, select PE and size(using TOTAL_ETF_ASSET_UNDER_MANAGEMENT as approximation); for bond index, select OAS,YTW, and TTM
  
questions:  
- why limiting T=100 and why do we use it to calculate omega_0 rather than the total time length?  
- How to solve the missing value problems? For convenient, I only use 10-year data here.
- why dropping TX60AR Index?
- How to introduce factor model/ BL method?

In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# pip install scikit-learn
# pip install openpyxl
from sklearn.decomposition import PCA
from numpy.linalg import inv
from statsmodels.stats.outliers_influence import variance_inflation_factor
#from names import bbg2name # colm change 0

In [40]:
# As I don't have access to bbg api， i create the mapping dictionary by myself and save it in the org_data1 sheet  2
## Load and Preprocess Data from 2004-2024; from six Russell and Bloomberg Barclays bond indices
index_data = pd.read_excel("data/org_data1.xlsx",sheet_name = "Sheet1")
#index_data.drop('TX60AR Index',axis=1,inplace=True) # colm change 1
# clean up blanks
fixblanks={x:x.replace("\u202f"," ") for x in list(index_data.columns)}
#yanni 0530
bbg2name = {
    "AS51 Index"   : "AU S&P/ASX 200",
    "SX5E Index"   : "EMU Stoxx 50",
    "MXEF Index"   : "MSCI Emerging Mkts",
    "NKY Index"    : "Japan Nikkei 225",
    "UKX Index"    : "UK FTSE 100",
    "TX60AR Index" : "CA S&P/TSX 60",
    "SPX Index"    : "US S&P 500",
    "FNRET Index"  : "US REITs",
    "I05500CA Index": "Canada Gov Bond",
    "I05510CA Index": "Canada Corp Bond",
    "LEATTREU Index": "EMU Gov Bond",
    "LSG1TRGU Index": "UK Gov Bond",
    "I38292JP Index": "Japan Gov Bond",
    "I12877US Index": "US Long Treasury",
    "BEMUTRUU Index": "EM Gov Bond",
    "BATY0 Index"  : "AU Corp Bond",
    "LC61TRGU Index": "UK Corp Bond",
    "LECPTREU Index": "EMU Corp Bond",
    "LJC1TRJU Index": "Japan Corp Bond",
    "BACR0 Index"  : "US Corp Bond",
    "LF98TRUU Index": "US High Yield",
    "LUMSTRUU Index": "US MBS"
}
index_data=index_data.rename(columns=fixblanks).rename(columns=bbg2name) # colm 1
index_data=index_data.rename(columns=fixblanks)
list(bbg2name[x] if x in bbg2name.keys() else 'not found' for x in list(index_data.columns))
#ndex_data.columns.sort_values()
#sorted(list(bbg2name.keys()))
#set(index_data.columns)-set(bbg2name.keys())
index_data['Date'] = pd.to_datetime(index_data['Date'])
index_data.set_index('Date', inplace=True)
index_returns = index_data.fillna(method='ffill').pct_change().dropna() # colm change 2
returns_clean = index_returns.dropna()
index_returns.to_csv('data/org_data_copy.csv') # colm 3

# Save index_returns to a pickle file
index_returns.to_pickle('data/rename_index_returns.pkl') # Save to pickle


# Test the collinearity

vif_data = pd.DataFrame()
vif_data["Asset"] = returns_clean.columns
vif_data["VIF"] = [variance_inflation_factor(returns_clean.values, i) for i in range(returns_clean.shape[1])]

print(vif_data)

                 Asset        VIF
0       AU S&P/ASX 200   3.732610
1         EMU Stoxx 50   4.864236
2   MSCI Emerging Mkts   3.658077
3     Japan Nikkei 225   3.145635
4          UK FTSE 100   3.862953
5        CA S&P/TSX 60   5.909261
6           US S&P 500   7.090241
7             US REITs   2.855731
8      Canada Gov Bond  14.696270
9     Canada Corp Bond  17.221845
10        EMU Gov Bond   9.463091
11         UK Gov Bond  16.275047
12      Japan Gov Bond   4.165122
13    US Long Treasury  13.280447
14         EM Gov Bond  10.660188
15        AU Corp Bond  17.763181
16        UK Corp Bond  20.582933
17       EMU Corp Bond  15.071300
18     Japan Corp Bond   4.548434
19        US Corp Bond  15.672495
20       US High Yield   8.258134
21              US MBS   4.430280

/var/folders/0_/90gvz7w52k50nmdszkztsq4r0000gn/T/ipykernel_10615/2732642360.py:40: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  index_returns = index_data.fillna(method='ffill').pct_change().dropna() # colm change 2

The VIF results indicate that several fixed income indices especially UK Corp Bond (20.58), AU Corp Bond (17.76), and Canada Corp Bond (17.22) exhibit high multicollinearity, suggesting they are strongly explained by other assets in the dataset. In contrast, equity indices generally show lower VIFs (mostly < 7), indicating less redundancy and better diversification potential.  
Doe this result make sense?

In [41]:
index_returns
##Japan gov bond and EM gov Bond contain missing values in the first ten years

,AU S&P/ASX 200,EMU Stoxx 50,MSCI Emerging Mkts,Japan Nikkei 225,UK FTSE 100,CA S&P/TSX 60,US S&P 500,US REITs,Canada Gov Bond,Canada Corp Bond,...,Japan Gov Bond,US Long Treasury,EM Gov Bond,AU Corp Bond,UK Corp Bond,EMU Corp Bond,Japan Corp Bond,US Corp Bond,US High Yield,US MBS
Date,,,,,,,,,,,,,,,,,,,,,
2013-05-31,-0.050980,0.021254,-0.029410,-0.006228,0.023790,0.023974,0.020763,-0.070685,-0.016734,-0.008596,...,-0.012476,-0.019590,-0.030698,-0.004983,-0.015802,-0.001836,-0.002116,3.381166e-03,-0.005796,-0.015333
2013-06-28,-0.025165,-0.060315,-0.067947,-0.007058,-0.055843,-0.038677,-0.014999,-0.047333,-0.016485,-0.015793,...,0.000114,-0.042559,-0.049811,-0.012094,-0.042134,-0.016439,0.001991,-6.125269e-03,-0.026226,-0.009619
2013-07-31,0.051928,0.063614,0.007678,-0.000658,0.065255,0.030152,0.049462,0.019168,0.000913,0.005703,...,0.002704,0.009937,0.017394,0.006650,0.024263,0.008463,0.001959,1.053227e-02,0.018957,-0.000900
2013-08-30,0.016425,-0.016899,-0.019007,-0.020446,-0.031435,0.019394,-0.031298,-0.088858,-0.005223,-0.004433,...,0.004717,-0.013681,-0.025222,-0.005134,-0.007459,-0.002071,0.001921,1.299660e-07,-0.006079,-0.002859
2013-09-30,0.016343,0.063123,0.062310,0.079689,0.007686,0.011314,0.029749,0.017936,0.004299,0.003995,...,0.005439,0.017936,0.025851,0.005097,0.009473,0.006706,0.001686,6.109442e-03,0.009931,0.014079
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31,-0.032845,0.019062,-0.002865,0.044140,-0.013790,-0.033552,-0.024990,-0.065983,-0.000871,0.002528,...,-0.000871,-0.008321,-0.012175,0.003655,-0.005659,-0.003762,0.000151,7.094234e-03,-0.004264,-0.016472
2025-01-31,0.045735,0.079839,0.016634,-0.008073,0.061292,0.041861,0.027016,-0.003745,0.011782,0.009918,...,-0.006737,0.008775,0.015981,0.001405,0.011578,0.004425,-0.004311,4.373247e-03,0.013663,0.005108
2025-02-28,-0.042186,0.033417,0.003549,-0.061078,0.015654,-0.004066,-0.014242,0.037111,0.011082,0.007286,...,-0.007623,0.017629,0.015692,0.008999,0.004979,0.005963,-0.002543,7.915734e-03,0.006714,0.025497
2025-03-31,-0.040249,-0.039379,0.003782,-0.041392,-0.025759,-0.019460,-0.057545,-0.040306,-0.001620,0.000034,...,-0.010077,0.000530,-0.011941,0.001167,-0.013158,-0.010403,-0.001806,2.843056e-03,-0.010223,-0.000171
2025-04-30,0.036054,-0.016799,0.010387,0.012011,-0.010248,0.000962,-0.007625,-0.036426,-0.006178,-0.003141,...,0.005561,-0.006278,-0.004170,0.018179,0.013659,0.009941,0.007469,1.092576e-02,-0.000203,0.002868

In [47]:
def simulate_sensitivity_model(index_returns, shrinkage_lambda=0,annualization_factor = 12 , gamma = 0.01, n_sim = 1000):
    T = 100 # index_returns.shape[0]
    n_assets = index_returns.shape[1]

    # Estimated covariance (annualized)
    Sigma = index_returns.cov().values * annualization_factor 
    vol = np.sqrt(np.diag(Sigma))
    vol_df = pd.DataFrame({
        'Asset': index_returns.columns,
        'Volatility': vol
    })
    
    # Apply shrinkage if needed
    if shrinkage_lambda > 0:
        # shrink_target = np.identity(n_assets) * np.trace(Sigma) / n_assets
        shrink_target = np.diag(np.diag(Sigma))
        Sigma = (1 - shrinkage_lambda) * Sigma + shrinkage_lambda * shrink_target


    # Omega_0 = covariance of theta
    Omega_0 = Sigma / T
    theta_0 = np.zeros((n_assets, 1))  # mean zero
    return MLBsim(Sigma,Omega_0,theta_0,gamma,n_sim)

def MLBsim(Sigma,Omega_0,theta_0,gamma,n_sim):
    # M² = trace(Sigma⁻¹) / n
    n_assets = Sigma.shape[0]
    Sigma_inv = np.linalg.inv(Sigma)
    trace_Sigma_inv = np.trace(Sigma_inv)
    M = np.sqrt(trace_Sigma_inv / n_assets)

    # L = 1 because Γ = Omega is fixed
    L = 1.0

    # Simulate theta and compute h
    h_1_norm_list = []
    h_2_norm_list = []

    for _ in range(n_sim):
        theta = np.random.multivariate_normal(mean=np.zeros(n_assets), cov=Omega_0).reshape(-1, 1)
        h = gamma * Sigma_inv @ theta
        h_1 = np.sum(np.abs(h))
        h_2 = np.sum(h ** 2)
        h_1_norm_list.append(h_1)
        h_2_norm_list.append(h_2)

    # Compute expectation estimates
    E_l1_squared = (np.mean(h_1_norm_list)) ** 2
    E_l2 = np.mean(h_2_norm_list)

    B = E_l1_squared / E_l2
    S = M * L * np.sqrt(B)

    return { "M": M, "L": L,"B": B, "S": S}

def simulate_sensitivity_pca_model(index_returns,annualization_factor=12, n_factors=None, gamma=0.01, n_sim=1000):
    n_returns, n_assets = index_returns.shape
    T=100
    returns_matrix = index_returns.values
    len(np.argwhere(np.isnan(returns_matrix)))
    Sigma = np.cov(returns_matrix.T) * annualization_factor 
    theta_0 = np.zeros((n_assets, 1))  # mean zero
    # === Step 1: PCA Decomposition ===
    n_factors = min(n_factors, T, n_assets)
    eigenvalues, eigenvectors = np.linalg.eigh(Sigma)
    evecn=eigenvectors[:,-n_factors:]
    evaln=eigenvalues[-n_factors:]
    Sigma_pca=evecn@np.diag(evaln)@evecn.T
    np.fill_diagonal(Sigma_pca, np.diag(Sigma))
    explained_variance_ratio= np.sum(evaln) / np.sum(eigenvalues)  # Explained variance ratio
    Omega_0= Sigma_pca / T
    mlb= MLBsim(Sigma_pca,Omega_0,theta_0,gamma,n_sim)
     
    mlb.update({"explained_variance_ratio":explained_variance_ratio, "n_factors": n_factors})
    return mlb
    

def run_sensitivity_analysis(index_returns, gamma, shrinkage_vec,n_factors_vec,T,time_windows):
    results_fixed = []
    results_random = []
    for window in time_windows:
        end_date = index_returns.index.max()
        start_date = end_date - pd.DateOffset(years=window)
        data_slice = index_returns[start_date:]
        #test different shrinkage rates
        for i in np.arange(len(shrinkage_vec)):
            result_random = simulate_sensitivity_model(data_slice,  gamma=gamma, shrinkage_lambda=shrinkage_vec[i])
            result_random.update({"Shrinkage Lambda": shrinkage_vec[i],"Time Window (Years)": window})
            results_random.append(result_random)
        # test the main factor contribution
        for i in np.arange(len(n_factors_vec)):
            #yanni0530
            nf = n_factors_vec[i]
            if nf > min(T, data_slice.shape[1]):
                continue  # skip if n_factors exceeds limit
            result_fixed = simulate_sensitivity_pca_model(data_slice,  n_factors=n_factors_vec[i],gamma=gamma)
            result_fixed.update({"Time Window (Years)": window})
            results_fixed.append(result_fixed)         
    results_df_fixed = pd.DataFrame(results_fixed)
    results_df_random = pd.DataFrame(results_random)
    return results_df_fixed,results_df_random

In [48]:
# Reload index_returns from the pickle file
returns_clean = pd.read_pickle('data/rename_index_returns.pkl') # Reload from pickle
shrinkage_vec = [0, 0.2, 0.4, 0.6, 0.8]
n_factors_vec=np.arange(0,24,1)

time_windows = [10]
gamma = 0.01
annualization_factor=12
T = 100

# Run and display
r0,r1 = run_sensitivity_analysis(returns_clean, gamma, shrinkage_vec,n_factors_vec, T,time_windows)
r1.to_csv("result_diff_shrinkage_rates.csv")
r0.to_csv("result_PCA.csv")

In [49]:
print(r0.sort_values(by=["Time Window (Years)","explained_variance_ratio"]))

            M    L         B           S  explained_variance_ratio  n_factors  \
1   32.148388  1.0  7.473565   87.886688                  0.633150          1
2   34.177109  1.0  8.081190   97.156753                  0.743164          2
3   36.758046  1.0  8.630445  107.986384                  0.818248          3
4   39.981421  1.0  9.161638  121.016557                  0.870039          4
5   40.821474  1.0  8.967969  122.246306                  0.902676          5
6   41.367509  1.0  9.296049  126.127147                  0.925330          6
7   42.806403  1.0  9.671725  133.125332                  0.943760          7
8   44.869706  1.0  9.922679  141.340851                  0.958343          8
9   45.338059  1.0  9.838235  142.207175                  0.968719          9
10  47.276923  1.0  9.875927  148.572397                  0.976914         10
11  49.209678  1.0  9.883381  154.704628                  0.982969         11
12  52.340921  1.0  9.895399  164.648590                  0.987077         12
13  57.180399  1.0  9.769850  178.727393                  0.990344         13
14  64.835334  1.0  9.301155  197.733473                  0.992912         14
15  69.409471  1.0  9.480269  213.712076                  0.995230         15
16  84.986976  1.0  8.661500  250.120300                  0.997035         16
17  93.304676  1.0  8.710515  275.375523                  0.998385         17
18  98.940863  1.0  8.013372  280.080813                  0.999275         18
19  95.971483  1.0  7.694533  266.215501                  0.999584         19
20  97.022292  1.0  7.040583  257.439889                  0.999842         20
21  88.159561  1.0  7.147641  235.695218                  0.999947         21
0   82.391067  1.0  7.631585  227.607993                  1.000000          0
22  82.391067  1.0  7.423561  224.484454                  1.000000         22

    Time Window (Years)
1                    10
2                    10
3                    10
4                    10
5                    10
6                    10
7                    10
8                    10
9                    10
10                   10
11                   10
12                   10
13                   10
14                   10
15                   10
16                   10
17                   10
18                   10
19                   10
20                   10
21                   10
0                    10
22                   10

In [50]:
print(r1)

           M    L         B           S  Shrinkage Lambda  Time Window (Years)
0  82.391067  1.0  7.497869  225.605170               0.0                   10
1  43.156419  1.0  6.612781  110.978144               0.2                   10
2  35.763096  1.0  6.634526   92.117057               0.4                   10
3  32.068834  1.0  5.981083   78.428350               0.6                   10
4  29.927669  1.0  6.019888   73.428912               0.8                   10

## Analysis
- The sensitivity decomposition results after data adjustment align well with expectations. In the PCA approach, the first five principal components account for over 90% of the variance, and 1% of risk corresponds to an average active share of 122%, which is consistent with the asset allocation case discussed in Section 7.1 of the paper. The number of investment opportunities is around 7–9, and the average position sizes also reflect realistic behavior.
- In the shrinkage method, a shrinkage rate of 0.2 already delivers notably improved results.

## Quarterly Data

In [51]:
index_returns

,AU S&P/ASX 200,EMU Stoxx 50,MSCI Emerging Mkts,Japan Nikkei 225,UK FTSE 100,CA S&P/TSX 60,US S&P 500,US REITs,Canada Gov Bond,Canada Corp Bond,...,Japan Gov Bond,US Long Treasury,EM Gov Bond,AU Corp Bond,UK Corp Bond,EMU Corp Bond,Japan Corp Bond,US Corp Bond,US High Yield,US MBS
Date,,,,,,,,,,,,,,,,,,,,,
2013-05-31,-0.050980,0.021254,-0.029410,-0.006228,0.023790,0.023974,0.020763,-0.070685,-0.016734,-0.008596,...,-0.012476,-0.019590,-0.030698,-0.004983,-0.015802,-0.001836,-0.002116,3.381166e-03,-0.005796,-0.015333
2013-06-28,-0.025165,-0.060315,-0.067947,-0.007058,-0.055843,-0.038677,-0.014999,-0.047333,-0.016485,-0.015793,...,0.000114,-0.042559,-0.049811,-0.012094,-0.042134,-0.016439,0.001991,-6.125269e-03,-0.026226,-0.009619
2013-07-31,0.051928,0.063614,0.007678,-0.000658,0.065255,0.030152,0.049462,0.019168,0.000913,0.005703,...,0.002704,0.009937,0.017394,0.006650,0.024263,0.008463,0.001959,1.053227e-02,0.018957,-0.000900
2013-08-30,0.016425,-0.016899,-0.019007,-0.020446,-0.031435,0.019394,-0.031298,-0.088858,-0.005223,-0.004433,...,0.004717,-0.013681,-0.025222,-0.005134,-0.007459,-0.002071,0.001921,1.299660e-07,-0.006079,-0.002859
2013-09-30,0.016343,0.063123,0.062310,0.079689,0.007686,0.011314,0.029749,0.017936,0.004299,0.003995,...,0.005439,0.017936,0.025851,0.005097,0.009473,0.006706,0.001686,6.109442e-03,0.009931,0.014079
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31,-0.032845,0.019062,-0.002865,0.044140,-0.013790,-0.033552,-0.024990,-0.065983,-0.000871,0.002528,...,-0.000871,-0.008321,-0.012175,0.003655,-0.005659,-0.003762,0.000151,7.094234e-03,-0.004264,-0.016472
2025-01-31,0.045735,0.079839,0.016634,-0.008073,0.061292,0.041861,0.027016,-0.003745,0.011782,0.009918,...,-0.006737,0.008775,0.015981,0.001405,0.011578,0.004425,-0.004311,4.373247e-03,0.013663,0.005108
2025-02-28,-0.042186,0.033417,0.003549,-0.061078,0.015654,-0.004066,-0.014242,0.037111,0.011082,0.007286,...,-0.007623,0.017629,0.015692,0.008999,0.004979,0.005963,-0.002543,7.915734e-03,0.006714,0.025497
2025-03-31,-0.040249,-0.039379,0.003782,-0.041392,-0.025759,-0.019460,-0.057545,-0.040306,-0.001620,0.000034,...,-0.010077,0.000530,-0.011941,0.001167,-0.013158,-0.010403,-0.001806,2.843056e-03,-0.010223,-0.000171
2025-04-30,0.036054,-0.016799,0.010387,0.012011,-0.010248,0.000962,-0.007625,-0.036426,-0.006178,-0.003141,...,0.005561,-0.006278,-0.004170,0.018179,0.013659,0.009941,0.007469,1.092576e-02,-0.000203,0.002868

In [52]:
# Convert to quarterly returns using compound returns:
index_returns_q = (1 + index_returns).resample('Q').prod() - 1
index_returns_q

/var/folders/0_/90gvz7w52k50nmdszkztsq4r0000gn/T/ipykernel_10615/2665370101.py:2: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  index_returns_q = (1 + index_returns).resample('Q').prod() - 1

,AU S&P/ASX 200,EMU Stoxx 50,MSCI Emerging Mkts,Japan Nikkei 225,UK FTSE 100,CA S&P/TSX 60,US S&P 500,US REITs,Canada Gov Bond,Canada Corp Bond,...,Japan Gov Bond,US Long Treasury,EM Gov Bond,AU Corp Bond,UK Corp Bond,EMU Corp Bond,Japan Corp Bond,US Corp Bond,US High Yield,US MBS
Date,,,,,,,,,,,,,,,,,,,,,
2013-06-30,-0.074863,-0.040343,-0.095358,-0.013242,-0.033382,-0.015630,0.005452,-0.114672,-0.032943,-0.024254,...,-0.012363,-0.061315,-0.078980,-0.017016,-0.057270,-0.018245,-0.000129,-0.002765,-0.031869,-0.024804
2013-09-30,0.086679,0.111643,0.050121,0.056918,0.039699,0.062012,0.046860,-0.054738,-0.000034,0.005244,...,0.012913,0.013987,0.017371,0.006586,0.026254,0.013123,0.005576,0.016706,0.022820,0.010270
2013-12-31,0.025549,0.074607,0.015423,0.126974,0.044392,0.076916,0.099200,0.010567,-0.003028,0.009327,...,0.001737,0.017383,0.016198,-0.002182,0.002211,0.009591,0.002316,0.008401,0.035817,-0.004174
2014-03-31,0.007962,0.016919,-0.008018,-0.089832,-0.022332,0.055181,0.012974,0.079599,0.023434,0.025862,...,0.007995,0.023264,0.037072,0.012260,0.023275,0.023597,0.003203,0.015186,0.029813,0.015854
2014-06-30,0.000170,0.021078,0.056432,0.022543,0.022062,0.063238,0.046941,0.054949,0.015413,0.015367,...,0.007587,0.040271,0.046102,0.032875,0.022569,0.023936,0.003268,0.024983,0.024077,0.024065
2014-09-30,-0.019077,-0.000716,-0.043254,0.066707,-0.017975,0.004304,0.006152,-0.030125,0.009315,0.006300,...,0.005841,-0.003063,-0.000553,0.009941,0.029299,0.018387,0.001599,0.011282,-0.018680,0.001823
2014-12-31,0.022333,-0.024644,-0.048760,0.078972,-0.008551,-0.003552,0.043913,0.112028,0.025523,0.014862,...,0.022848,-0.020833,-0.006212,0.044618,0.044641,0.015537,0.004678,0.026990,-0.010022,0.017864
2015-03-31,0.088798,0.175103,0.019094,0.100639,0.031518,0.024161,0.004366,0.051139,0.035026,0.031694,...,-0.005024,0.021312,0.021547,0.030800,0.034451,0.013597,-0.001789,0.022119,0.025219,0.010573
2015-06-30,-0.073410,-0.073858,-0.002381,0.053561,-0.037215,-0.017522,-0.002312,-0.131326,-0.015081,-0.008329,...,-0.002223,0.014400,-0.001146,-0.027091,-0.041852,-0.029006,0.001282,-0.006990,0.000030,-0.007442
2015-09-30,-0.080121,-0.094510,-0.185343,-0.140720,-0.070445,-0.067435,-0.069352,0.032867,0.010679,-0.001755,...,0.008192,-0.037324,-0.015524,0.024976,0.006177,-0.002624,0.002055,0.015142,-0.048564,0.013042
2015-12-31,0.054610,0.053811,0.002639,0.094637,0.029812,-0.017007,0.064535,0.069821,0.006677,0.005368,...,0.010633,-0.000599,0.010497,-0.004572,0.009750,0.012994,0.001749,-0.000177,-0.020648,-0.001025
2016-03-31,-0.040234,-0.080364,0.053718,-0.119527,-0.010800,0.042397,0.007730,0.073144,0.011170,0.012436,...,0.042275,0.044077,0.047112,0.023316,0.031748,0.024640,0.004854,0.014234,0.033534,0.019766
2016-06-30,0.029627,-0.046653,-0.003227,-0.070575,0.053350,0.042437,0.018993,0.063814,0.020463,0.021904,...,0.027359,0.038783,0.048684,0.033264,0.047139,0.015733,0.004744,0.023327,0.055189,0.011063
2016-09-30,0.038703,0.047997,0.083155,0.056107,0.060729,0.057722,0.033070,-0.034272,0.005532,0.016002,...,-0.019599,0.025932,0.042834,0.008116,0.064068,0.018438,-0.000583,0.014206,0.055511,0.005963
2016-12-31,0.042287,0.096022,-0.045591,0.161979,0.035293,0.055898,0.032542,-0.117046,-0.039483,-0.012888,...,-0.016875,-0.005371,-0.035467,-0.038305,-0.023400,-0.011959,-0.001654,-0.014026,0.017536,-0.019728
2017-03-31,0.035143,0.063944,0.111450,-0.010731,0.025213,0.024419,0.055337,-0.056316,0.006067,0.017234,...,-0.003861,0.029635,0.037364,0.012022,0.019147,0.002680,0.001142,0.017057,0.026992,0.004729
2017-06-30,-0.024452,-0.016867,0.054707,0.059451,-0.001393,-0.017791,0.025686,-0.086948,0.003265,0.004860,...,0.000440,0.017150,0.022587,0.010778,0.005487,0.003551,0.001438,0.011117,0.021720,0.008702
2017-09-30,-0.006971,0.044444,0.070162,0.016116,0.008210,0.039791,0.039593,0.001438,-0.017956,-0.010421,...,0.001454,0.022414,0.028401,-0.004162,0.001278,0.011279,0.001796,0.006852,0.019755,0.009594
2017-12-31,0.067502,-0.025283,0.070933,0.118325,0.042726,0.049318,0.061226,0.053796,0.009943,0.016047,...,0.003693,0.008557,0.014229,0.015934,0.022007,0.006420,0.001432,0.014932,0.004689,0.001505
2018-03-31,-0.050413,-0.040657,0.010730,-0.057573,-0.082099,-0.046110,-0.012246,-0.122679,0.004120,0.001172,...,0.004034,-0.012880,-0.014510,0.010238,-0.015289,-0.003938,0.001487,0.008084,-0.008580,-0.011932
2018-06-30,0.075576,0.010144,-0.086567,0.039629,0.082238,0.070867,0.029346,0.087642,0.003278,0.004504,...,0.002260,-0.019029,-0.034314,0.007650,-0.003427,-0.002501,0.000606,0.007281,0.010268,0.002415
2018-09-30,0.002087,0.001060,-0.020205,0.081397,-0.016594,-0.006549,0.071959,0.019081,-0.010182,-0.003596,...,-0.010308,0.014553,0.022550,0.004588,-0.003061,0.000030,-0.001267,0.008600,0.024039,-0.001178
2018-12-31,-0.090400,-0.117022,-0.078375,-0.170202,-0.104134,-0.089294,-0.139716,-0.070754,0.028043,0.007393,...,0.013739,-0.001348,-0.008598,0.027570,-0.000724,-0.006160,0.003359,0.014739,-0.045339,0.020832
2019-03-31,0.094632,0.116708,0.095622,0.059508,0.081904,0.125398,0.130662,0.131104,0.025542,0.040733,...,0.014788,0.053834,0.067527,0.039344,0.045743,0.031952,0.002766,0.028525,0.072579,0.021672
2019-06-30,0.070872,0.036393,-0.003090,0.003306,0.020118,0.029822,0.037878,-0.078765,0.015909,0.026551,...,0.009428,0.031363,0.043151,0.034274,0.022878,0.021565,0.003517,0.026694,0.025006,0.019611
2019-09-30,0.010512,0.027567,-0.051059,0.022557,-0.002346,0.026940,0.011891,0.047520,0.009482,0.009509,...,0.005464,0.015595,0.009634,0.022354,0.039827,0.012943,0.002176,0.017632,0.013339,0.013720
2019-12-31,-0.000639,0.049223,0.113546,0.087369,0.018119,0.024479,0.085342,-0.035070,-0.013778,0.001012,...,-0.012396,0.024952,0.016091,-0.018704,-0.002359,-0.005101,-0.004389,-0.003743,0.026148,0.007123
2020-03-31,-0.240459,-0.255864,-0.238710,-0.200350,-0.247994,-0.184821,-0.200011,-0.494901,0.056740,-0.025395,...,-0.003520,-0.088588,-0.143863,0.040816,-0.052797,-0.061506,-0.003656,0.007485,-0.126848,0.028192
2020-06-30,0.161726,0.160454,0.172665,0.178206,0.087762,0.149877,0.199529,0.217799,0.021495,0.077901,...,-0.005810,0.106464,0.124407,-0.002261,0.090261,0.052830,-0.000410,0.015780,0.101774,0.006657
2020-09-30,-0.013893,-0.012511,0.087328,0.040245,-0.049214,0.044133,0.084737,-0.053031,-0.001203,0.013736,...,0.001257,0.026773,0.023230,0.007809,0.015244,0.019921,0.003262,0.015049,0.045960,0.001106
2020-12-31,0.132593,0.112421,0.193401,0.183698,0.101331,0.078589,0.116881,0.215310,-0.004195,0.017972,...,-0.000326,0.043798,0.062449,-0.005739,0.040476,0.019803,0.003942,0.013532,0.064506,0.002451
2021-03-31,0.030905,0.103182,0.019493,0.063206,0.039178,0.087966,0.057725,0.171188,-0.041416,-0.033324,...,-0.004092,-0.013033,-0.045409,-0.038864,-0.046830,-0.006825,0.001500,-0.014260,0.008499,-0.011001
2021-06-30,0.076923,0.037020,0.044218,-0.013272,0.048236,0.090017,0.081706,0.113583,0.008027,0.012135,...,0.002508,0.020629,0.042271,0.018741,0.019658,0.002939,0.004175,0.010904,0.027431,0.003338
2021-09-30,0.002617,-0.003991,-0.088416,0.022963,0.006956,0.002056,0.002336,-0.017822,-0.004736,-0.000699,...,0.000779,-0.016095,-0.007297,0.003715,-0.010417,0.000800,0.000534,0.002681,0.008858,0.000980
2021-12-31,0.015341,0.061839,-0.016830,-0.022441,0.042069,0.077512,0.106474,0.139541,0.010959,0.009261,...,-0.000972,-0.020907,-0.009774,-0.014502,0.005812,-0.006566,0.000967,-0.015489,0.007107,-0.003726
2022-03-31,0.007381,-0.092101,-0.073230,-0.033700,0.017759,0.034707,-0.049467,-0.076958,-0.057233,-0.063911,...,-0.015982,-0.098545,-0.109990,-0.062629,-0.067455,-0.049583,-0.005718,-0.046307,-0.048366,-0.049730
2022-06-30,-0.124210,-0.114710,-0.123595,-0.051341,-0.046090,-0.126457,-0.164451,-0.157839,-0.044989,-0.045261,...,-0.013809,-0.070361,-0.128401,-0.037802,-0.079732,-0.072860,-0.003256,-0.032262,-0.098289,-0.040053
2022-09-30,-0.014291,-0.039556,-0.124796,-0.017271,-0.038424,-0.017311,-0.052771,-0.083378,0.002318,0.000188,...,-0.006355,-0.042255,-0.050431,-0.007152,-0.119860,-0.030583,-0.002182,-0.000664,-0.006463,-0.053496
2022-12-31,0.087191,0.143276,0.092020,0.006064,0.080932,0.055562,0.070805,0.160756,-0.001200,0.012398,...,-0.019373,0.060862,0.093539,0.002366,0.068735,0.010914,-0.010436,0.011161,0.041711,0.021409
2023-03-31,0.019757,0.137449,0.035446,0.074613,0.024155,0.041097,0.070272,-0.026954,0.029176,0.027389,...,0.024155,0.020214,0.014553,0.048898,0.024725,0.017511,0.007875,0.034355,0.035681,0.025261
2023-06-30,0.003559,0.019476,-0.000808,0.183569,-0.013131,0.015494,0.082999,-0.004740,-0.015326,0.000552,...,0.003863,0.005212,0.028265,-0.036379,-0.034179,0.004258,0.006045,-0.011449,0.017478,-0.006446
2023-09-30,-0.021471,-0.051017,-0.037090,-0.040116,0.010164,-0.025484,-0.036476,-0.096037,-0.034836,-0.020109,...,-0.031545,-0.015984,-0.018574,-0.007959,0.022104,0.003392,-0.009779,0.012557,0.004580,-0.040543
2023-12-31,0.076920,0.083068,0.074477,0.050429,0.016451,0.087570,0.112354,0.197980,0.073597,0.074236,...,0.009277,0.056843,0.094481,0.039798,0.085349,0.055165,0.007376,0.031751,0.071646,0.074798
2024-03-31,0.040317,0.124292,0.019009,0.206348,0.028368,0.063308,0.101580,-0.006496,-0.014361,0.000729,...,-0.005888,0.022335,0.026831,0.009496,0.001064,0.004654,0.000693,0.013662,0.014746,-0.010446
2024-06-30,-0.016385,-0.037258,0.041267,-0.019479,0.026595,-0.013436,0.039230,-0.015554,0.008295,0.011039,...,-0.026538,0.012642,0.001454,-0.010063,-0.004519,0.000755,-0.005783,0.002255,0.010940,0.000693
2024-09-30,0.064675,0.021747,0.077883,-0.042026,0.008921,0.111648,0.055306,0.164597,0.041513,0.045969,...,0.014999,0.048434,0.066325,0.028990,0.023867,0.032735,0.006849,0.030560,0.052833,0.055292
2024-12-31,-0.013384,-0.020892,-0.081454,0.052084,-0.007761,0.037973,0.020677,-0.044809,-0.005428,0.009715,...,-0.013994,-0.014608,-0.014513,-0.005542,-0.003162,0.008697,-0.006145,0.006738,0.001747,-0.031575
2025-03-31,-0.038695,0.071979,0.024101,-0.107207,0.050139,0.017431,-0.045868,-0.008418,0.021337,0.017311,...,-0.024242,0.027103,0.019601,0.011596,0.003238,-0.000097,-0.008638,0.015202,0.010037,0.030559
2025-06-30,0.036054,-0.016799,0.010387,0.012011,-0.010248,0.000962,-0.007625,-0.036426,-0.006178,-0.003141,...,0.005561,-0.006278,-0.004170,0.018179,0.013659,0.009941,0.007469,0.010926,-0.000203,0.002868

In [54]:
shrinkage_vec = [0, 0.2, 0.4, 0.6, 0.8]
n_factors_vec=np.arange(0,24,1)

time_windows = [10]
gamma = 0.01
annualization_factor=4
T=100

# Run and display
r2,r3 = run_sensitivity_analysis(index_returns_q, gamma, shrinkage_vec,n_factors_vec, T, time_windows)

In [55]:
r2

,M,L,B,S,explained_variance_ratio,n_factors,Time Window (Years)
0,63.331207,1.0,8.139571,180.683510,1.000000,0,10
1,18.197513,1.0,7.695607,50.481640,0.673765,1,10
2,20.036234,1.0,8.639577,58.892819,0.797434,2,10
3,22.342999,1.0,9.274983,68.045284,0.874593,3,10
4,24.812261,1.0,9.714849,77.336474,0.909379,4,10
5,25.969218,1.0,9.338566,79.359508,0.934025,5,10
6,26.461019,1.0,9.605599,82.010372,0.950968,6,10
7,27.397109,1.0,10.066547,86.925059,0.964265,7,10
8,29.647732,1.0,10.534945,96.229365,0.973952,8,10
9,32.961390,1.0,10.002861,104.247976,0.981009,9,10
10,34.079516,1.0,10.152646,108.588300,0.986027,10,10
11,36.628551,1.0,10.425159,118.266319,0.989976,11,10
12,40.673992,1.0,9.728237,126.862674,0.992899,12,10
13,46.042612,1.0,9.516035,142.032575,0.994973,13,10
14,50.293834,1.0,9.844929,157.805101,0.996563,14,10
15,60.386288,1.0,9.281487,183.970041,0.997613,15,10
16,63.275121,1.0,9.128106,191.171577,0.998550,16,10
17,67.648272,1.0,8.904138,201.861106,0.999172,17,10
18,72.883061,1.0,8.437999,211.712415,0.999644,18,10
19,77.476461,1.0,8.345890,223.823710,0.999791,19,10
20,86.172165,1.0,7.537265,236.577753,0.999926,20,10
21,74.305480,1.0,7.675958,205.867192,0.999970,21,10
22,63.331207,1.0,8.100463,180.248930,1.000000,22,10

In [57]:
r3

           M    L         B           S  Shrinkage Lambda  Time Window (Years)
0  63.331207  1.0  8.056592  179.760168               0.0                   10
1  25.028392  1.0  6.646026   64.522913               0.2                   10
2  20.353863  1.0  6.300746   51.090817               0.4                   10
3  18.101557  1.0  6.214337   45.124596               0.6                   10
4  16.829072  1.0  5.858306   40.732980               0.8                   10

## Alpha Factor Construction